// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:unsplashed_client/utils/unsplashed_keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: UnsplashedKeys.firebaseWebApiKey,
    appId: UnsplashedKeys.firebaseWebApiId,
    messagingSenderId: UnsplashedKeys.messagingWebCenterId,
    projectId: 'unsplashedflutterclient',
    authDomain: 'unsplashedflutterclient.firebaseapp.com',
    storageBucket: 'unsplashedflutterclient.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: UnsplashedKeys.firebaseAndroiApiKey,
    appId: UnsplashedKeys.firebaseAndroidApiId,
    messagingSenderId: UnsplashedKeys.messagingAndroidCenterId,
    projectId: 'unsplashedflutterclient',
    storageBucket: 'unsplashedflutterclient.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: UnsplashedKeys.firebaseIosApiKey,
    appId: UnsplashedKeys.firebaseIosApiId,
    messagingSenderId: UnsplashedKeys.messagingIosCenterId,
    projectId: 'unsplashedflutterclient',
    storageBucket: 'unsplashedflutterclient.appspot.com',
    iosClientId:
        '663337347368-keeo3mmfqks1e73o11obhpr9jvrvlve4.apps.googleusercontent.com',
    iosBundleId: 'com.unsplashedclient',
  );
}
